"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hw63ll^-5&rcm5#4lxruu#51hu0$60+9wk3o6qpm^pf+7uu%kl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home.apps.HomeConfig',
    'algoritimos_e_logica_de_programacao.apps.AlgoritimosELogicaDeProgramacaoConfig',
    'banco_de_dados.apps.BancoDeDadosConfig',
    'big_data.apps.BigDataConfig',
    'calculo_diferencial_e_integral.apps.CalculoDiferencialEIntegralConfig',
    'comunicacao_ead.apps.ComunicacaoEadConfig',
    'desenvolvimento_para_dispositivos_moveis.apps.DesenvolvimentoParaDispositivosMoveisConfig',
    'desenvolvimento_para_jogos_digitais.apps.DesenvolvimentoParaJogosDigitaisConfig',
    'empreendedorismo_ead.apps.EmpreendedorismoEadConfig',
    'engenharia_de_economica.apps.EngenhariaDeEconomicaConfig',
    'engenharia_de_software_analise_e_projeto_de_software.apps.EngenhariaDeSoftwareAnaliseEProjetoDeSoftwareConfig',
    'engenharia_de_software_arquitetura_de_software.apps.EngenhariaDeSoftwareArquiteturaDeSoftwareConfig',
    'engenharia_de_software_modelagem_de_software.apps.EngenhariaDeSoftwareModelagemDeSoftwareConfig',
    'engenharia_de_software_qualidade_de_software.apps.EngenhariaDeSoftwareQualidadeDeSoftwareConfig',
    'engenharia_de_software_processos_e_requisitos.apps.EngenhariaDeSoftwareProcessosERequisitosConfig',
    'engenharia_de_software_metodos_de_desenvolvimento.apps.EngenhariaDeSoftwareMetodosDeDesenvolvimentoConfig',
    'estagio_supervisionado_I.apps.EstagioSupervisionadoIConfig',
    'estagio_supervisionado_II.apps.EstagioSupervisionadoIiConfig',
    'estrutura_de_dados.apps.EstruturaDeDadosConfig',
    'filosofia_ead.apps.FilosofiaEadConfig',
    'gestao_de_projetos.apps.GestaoDeProjetosConfig',
    'inovacoes_tecnologicas.apps.InovacoesTecnologicasConfig',
    'inteligencia_artificial.apps.InteligenciaArtificialConfig',
    'interface_homem_computador.apps.InterfaceHomemComputadorConfig',
    'internet_das_coisas_iot.apps.InternetDasCoisasIotConfig',
    'introducao_a_engenharia_de_software.apps.IntroducaoAEngenhariaDeSoftwareConfig',
    'linguagem_de_programacao.apps.LinguagemDeProgramacaoConfig',
    'logica_matematica.apps.LogicaMatematicaConfig',
    'matematica_discreta.apps.MatematicaDiscretaConfig',
    'metodologia_ead.apps.MetodologiaEadConfig',
    'metodologias_ageis.apps.MetodologiasAgeisConfig',
    'organizacao_e_redes_de_computadores.apps.OrganizacaoERedesDeComputadoresConfig',
    'pesquisa_operacional.apps.PesquisaOperacionalConfig',
    'probabilidade_estatistica.apps.ProbabilidadeEstatisticaConfig',
    'programaca_web.apps.ProgramacaWebConfig',
    'projeto_de_designe_de_software.apps.ProjetoDeDesigneDeSoftwareConfig',
    'projeto_de_programacao_banco_de_dados.apps.ProjetoDeProgramacaoBancoDeDadosConfig',
    'projeto_desenvolvimento_professional_I.apps.ProjetoDesenvolvimentoProfessionalIConfig',
    'projeto_desenvolvimento_professional_II.apps.ProjetoDesenvolvimentoProfessionalIiConfig',
    'projeto_integracao_software.apps.ProjetoIntegracaoSoftwareConfig',
    'projeto_mineracao_dados.apps.ProjetoMineracaoDadosConfig',
    'projeto_orientado_a_objetos.apps.ProjetoOrientadoAObjetosConfig',
    'projeto_programacao_web.apps.ProjetoProgramacaoWebConfig',
    'sociologia_ead.apps.SociologiaEadConfig',
    'sustentabilidade_ead.apps.SustentabilidadeEadConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'pages')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
